server:
  port: 7001

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations:
        - file:${user.dir}/assets/
        - classpath:/assets/